In [1]:
import tensorflow as tf
tf.random.set_seed(777)

In [2]:
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [3]:
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

In [4]:
# convert to tensor
X = tf.constant(x_data, dtype=tf.float32)
Y = tf.constant(y_data, dtype=tf.float32)
X_test = tf.constant(x_test, dtype=tf.float32)
Y_test = tf.constant(y_test, dtype=tf.float32)

In [5]:
W = tf.Variable(tf.random.normal([3, 3]), name='weight')
b = tf.Variable(tf.random.normal([3]), name='bias')

In [6]:
# hypothesis
def hypothesis(X):
    return tf.nn.softmax(tf.matmul(X, W) + b)

# cross entropy cost
def cost_function(hypothesis, Y):
    return tf.reduce_mean(-tf.reduce_mean(Y * tf.math.log(hypothesis), axis=1))

# optimize/minimize
optimizer = tf.optimizers.SGD(learning_rate=0.1)

In [7]:
# prediction
def predicted(hypothesis):
    return tf.argmax(hypothesis, 1)

# accuracy
def accuracy(predict, Y):
    return tf.reduce_mean(tf.cast(tf.equal(predict, tf.argmax(Y, 1)), tf.float32))

In [8]:
# training
for step in range(201):
    with tf.GradientTape() as tape:
        current_cost = cost_function(hypothesis(X), Y)
    gradients = tape.gradient(current_cost, [W, b])
    optimizer.apply_gradients(zip(gradients, [W, b]))
    
    print(step, current_cost.numpy(), W)

0 3.8377728 <tf.Variable 'weight:0' shape=(3, 3) dtype=float32, numpy=
array([[ 0.7789605 ,  0.38584462, -0.07656625],
       [ 0.05770724, -0.531522  ,  1.4578416 ],
       [ 0.300233  , -0.03669946,  1.3252047 ]], dtype=float32)>
1 3.4305615 <tf.Variable 'weight:0' shape=(3, 3) dtype=float32, numpy=
array([[ 0.787256  ,  0.3983276 , -0.09734467],
       [ 0.1117947 , -0.47322333,  1.3454555 ],
       [ 0.35435528,  0.02578253,  1.2086005 ]], dtype=float32)>
2 3.0237198 <tf.Variable 'weight:0' shape=(3, 3) dtype=float32, numpy=
array([[ 0.79551965,  0.41079658, -0.11807732],
       [ 0.16581301, -0.41495362,  1.2331675 ],
       [ 0.40843263,  0.08824858,  1.0920571 ]], dtype=float32)>
3 2.6176085 <tf.Variable 'weight:0' shape=(3, 3) dtype=float32, numpy=
array([[ 0.80372137,  0.42323983, -0.13872229],
       [ 0.2196924 , -0.3567381 ,  1.1210726 ],
       [ 0.46240667,  0.15068267,  0.975649  ]], dtype=float32)>
4 2.2130291 <tf.Variable 'weight:0' shape=(3, 3) dtype=float32, numpy=
a

68 0.29993147 <tf.Variable 'weight:0' shape=(3, 3) dtype=float32, numpy=
array([[6.5521473e-01, 4.3272218e-01, 3.0182209e-04],
       [3.8534707e-01, 1.5692656e-01, 4.4175342e-01],
       [6.6347718e-01, 6.9884902e-01, 2.2641221e-01]], dtype=float32)>
69 0.2994281 <tf.Variable 'weight:0' shape=(3, 3) dtype=float32, numpy=
array([[0.65269756, 0.43130505, 0.00423614],
       [0.38551962, 0.15724361, 0.44126382],
       [0.66430604, 0.6991682 , 0.22526415]], dtype=float32)>
70 0.2989276 <tf.Variable 'weight:0' shape=(3, 3) dtype=float32, numpy=
array([[0.65018576, 0.4298937 , 0.00815929],
       [0.38569337, 0.157561  , 0.44077268],
       [0.6651317 , 0.699485  , 0.22412169]], dtype=float32)>
71 0.29842985 <tf.Variable 'weight:0' shape=(3, 3) dtype=float32, numpy=
array([[0.6476793 , 0.4284881 , 0.01207131],
       [0.38586828, 0.15787873, 0.44028005],
       [0.6659541 , 0.6997994 , 0.22298482]], dtype=float32)>
72 0.2979349 <tf.Variable 'weight:0' shape=(3, 3) dtype=float32, numpy=
arr

131 0.27304614 <tf.Variable 'weight:0' shape=(3, 3) dtype=float32, numpy=
array([[0.50635386, 0.3540699 , 0.22781484],
       [0.39786583, 0.17720324, 0.4089581 ],
       [0.7103767 , 0.71471906, 0.16364236]], dtype=float32)>
132 0.272688 <tf.Variable 'weight:0' shape=(3, 3) dtype=float32, numpy=
array([[0.50413704, 0.35298386, 0.23111765],
       [0.39808148, 0.17752437, 0.40842134],
       [0.7110483 , 0.71491003, 0.16277976]], dtype=float32)>
133 0.27233174 <tf.Variable 'weight:0' shape=(3, 3) dtype=float32, numpy=
array([[0.5019244 , 0.3519025 , 0.23441163],
       [0.3982974 , 0.17784531, 0.40788448],
       [0.7117181 , 0.71509933, 0.16192064]], dtype=float32)>
134 0.27197728 <tf.Variable 'weight:0' shape=(3, 3) dtype=float32, numpy=
array([[0.4997159 , 0.35082585, 0.2376968 ],
       [0.39851356, 0.17816606, 0.4073476 ],
       [0.712386  , 0.7152871 , 0.16106497]], dtype=float32)>
135 0.27162465 <tf.Variable 'weight:0' shape=(3, 3) dtype=float32, numpy=
array([[0.4975115 , 0.34

197 0.2528344 <tf.Variable 'weight:0' shape=(3, 3) dtype=float32, numpy=
array([[0.36819667, 0.29165694, 0.42838496],
       [0.41223747, 0.19771089, 0.37407875],
       [0.7513906 , 0.72436804, 0.11297938]], dtype=float32)>
198 0.2525742 <tf.Variable 'weight:0' shape=(3, 3) dtype=float32, numpy=
array([[0.36621925, 0.2908437 , 0.43117562],
       [0.41245198, 0.19800724, 0.37356788],
       [0.75196975, 0.7244759 , 0.11229231]], dtype=float32)>
199 0.25231516 <tf.Variable 'weight:0' shape=(3, 3) dtype=float32, numpy=
array([[0.36424497, 0.29003403, 0.43395957],
       [0.41266626, 0.19830307, 0.37305775],
       [0.752548  , 0.72458285, 0.11160717]], dtype=float32)>
200 0.25205728 <tf.Variable 'weight:0' shape=(3, 3) dtype=float32, numpy=
array([[0.3622738 , 0.28922793, 0.43673682],
       [0.4128803 , 0.19859838, 0.3725484 ],
       [0.7531252 , 0.7246889 , 0.11092395]], dtype=float32)>


In [9]:
# evaluation
predict = predicted(hypothesis(X_test))
print("Prediction: ", predict.numpy())
print("Accuracy: ", accuracy(predict, Y_test).numpy())

Prediction:  [2 2 1]
Accuracy:  0.6666667
