In [1]:
import tensorflow as tf
import numpy as np
from sklearn.preprocessing import MinMaxScaler
tf.random.set_seed(777)

In [2]:
xy = np.array(
    [
        [828.659973, 833.450012, 908100, 828.349976, 831.659973],
        [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
        [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
        [816, 820.958984, 1008100, 815.48999, 819.23999],
        [819.359985, 823, 1188100, 818.469971, 818.97998],
        [819, 823, 1198100, 816, 820.450012],
        [811.700012, 815.25, 1098100, 809.780029, 813.669983],
        [809.51001, 816.659973, 1398100, 804.539978, 809.559998],
    ]
)

In [3]:
scaler = MinMaxScaler()
xy = scaler.fit_transform(xy)
print(xy)

[[1.         1.         0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881783 0.83755792]
 [0.54412549 0.50274824 0.57608696 0.60646801 0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.4258239  0.30434783 0.58504805 0.42624401]
 [0.49556179 0.4258239  0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [4]:
x_data = xy[:, :-1]
y_data = xy[:, [-1]]

In [5]:
X = tf.constant(x_data, dtype=tf.float32)
Y = tf.constant(y_data, dtype=tf.float32)

W = tf.Variable(tf.random.normal([4, 1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')

In [6]:
# hypothesis
def hypothesis(X):
    return tf.matmul(X, W) + b

# cost_function
def cost_function(hypothesis, Y):
    return tf.reduce_mean(tf.square(hypothesis - Y))

# opmtimize
optimizer = tf.optimizers.SGD(learning_rate = 0.1)

In [7]:
# trainiing
for step in range(2001):
    with tf.GradientTape() as tape:
        current_cost = cost_function(hypothesis(X), Y)
    gradients = tape.gradient(current_cost, [W, b])
    optimizer.apply_gradients(zip(gradients, [W, b]))
    
    if step % 20 == 0:
        print(step, "Cost:", current_cost.numpy(), hypothesis(X).numpy())

0 Cost: 1.7346182 [[ 0.46375597]
 [ 0.0672878 ]
 [-0.20887744]
 [-0.52464545]
 [-0.28817743]
 [-0.3184142 ]
 [-0.90412164]
 [-0.9829137 ]]
20 Cost: 0.04384502 [[ 1.2388716 ]
 [ 1.0189874 ]
 [ 0.63823175]
 [ 0.20443612]
 [ 0.49868268]
 [ 0.46128047]
 [-0.1828797 ]
 [-0.2151529 ]]
40 Cost: 0.01808035 [[ 1.1107299 ]
 [ 0.97110003]
 [ 0.63576686]
 [ 0.25267458]
 [ 0.50897914]
 [ 0.4807207 ]
 [-0.0620019 ]
 [-0.07614893]]
60 Cost: 0.009755059 [[ 1.0499185 ]
 [ 0.9329248 ]
 [ 0.6308894 ]
 [ 0.28464442]
 [ 0.51667345]
 [ 0.49266607]
 [ 0.00710952]
 [-0.00511113]]
80 Cost: 0.0066744136 [[1.0222661 ]
 [0.9032197 ]
 [0.62574804]
 [0.30649295]
 [0.52247894]
 [0.5002724 ]
 [0.04800111]
 [0.03116736]]
100 Cost: 0.005355272 [[1.0106251 ]
 [0.8804364 ]
 [0.62117213]
 [0.32179958]
 [0.5268818 ]
 [0.505261  ]
 [0.0731246 ]
 [0.04962948]]
120 Cost: 0.004716691 [[1.0064809 ]
 [0.86312675]
 [0.6174069 ]
 [0.3327381 ]
 [0.5302405 ]
 [0.50861204]
 [0.08917571]
 [0.05893698]]
140 Cost: 0.00437953 [[1.0056626

1240 Cost: 0.00341442 [[1.0002356 ]
 [0.8147686 ]
 [0.61339355]
 [0.37010825]
 [0.5509177 ]
 [0.50932014]
 [0.13909434]
 [0.04400473]]
1260 Cost: 0.0034090697 [[1.0000705 ]
 [0.81482303]
 [0.6135095 ]
 [0.3702194 ]
 [0.55105126]
 [0.5091986 ]
 [0.13926816]
 [0.04369429]]
1280 Cost: 0.0034038294 [[0.9999078 ]
 [0.8148768 ]
 [0.613624  ]
 [0.3703298 ]
 [0.55118275]
 [0.5090778 ]
 [0.13943939]
 [0.04338824]]
1300 Cost: 0.0033986918 [[0.99974734]
 [0.81492996]
 [0.6137371 ]
 [0.3704395 ]
 [0.5513124 ]
 [0.5089578 ]
 [0.13960806]
 [0.04308656]]
1320 Cost: 0.003393656 [[0.9995891 ]
 [0.81498253]
 [0.61384887]
 [0.37054843]
 [0.5514401 ]
 [0.50883853]
 [0.13977422]
 [0.04278912]]
1340 Cost: 0.003388718 [[0.9994331 ]
 [0.81503445]
 [0.6139593 ]
 [0.37065658]
 [0.55156595]
 [0.5087201 ]
 [0.13993788]
 [0.04249594]]
1360 Cost: 0.0033838744 [[0.9992793 ]
 [0.8150857 ]
 [0.6140683 ]
 [0.37076405]
 [0.55168986]
 [0.50860226]
 [0.1400991 ]
 [0.04220689]]
1380 Cost: 0.0033791251 [[0.99912775]
 [0.815