In [1]:
import tensorflow as tf
import numpy as np
tf.random.set_seed(777) # for reproducibility

In [2]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [3]:
# Check data
print(x_data,"\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)


In [4]:
X = tf.keras.Input(shape=(3, ), dtype=tf.float32)
Y = tf.keras.Input(shape=(1, ), dtype=tf.float32)

W = tf.Variable(tf.random.normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random.normal([1]), name = 'bias')

In [5]:
X = x_data
Y = y_data

In [6]:
# hypothesis
def hypothesis(X):
    return tf.matmul(X, W) + b

# cost function
def cost_function(hypothesis, Y):
    return tf.reduce_mean(tf.square(hypothesis - Y))

# optimize/minimize
optimizer = tf.optimizers.SGD(learning_rate = 1e-5)

In [7]:
# training
for step in range(2001):
    with tf.GradientTape() as tape:
        current_cost = cost_function(hypothesis(X), Y)
    gradients = tape.gradient(current_cost, [W, b])
    optimizer.apply_gradients(zip(gradients, [W, b]))
    
    if step % 20 == 0:
        print(step, "Cost:", current_cost.numpy())

0 Cost: 6115.098
20 Cost: 27.715788
40 Cost: 27.40089
60 Cost: 27.090889
80 Cost: 26.78563
100 Cost: 26.485085
120 Cost: 26.189215
140 Cost: 25.897852
160 Cost: 25.610989
180 Cost: 25.328485
200 Cost: 25.050423
220 Cost: 24.776545
240 Cost: 24.506851
260 Cost: 24.241331
280 Cost: 23.979849
300 Cost: 23.722343
320 Cost: 23.4688
340 Cost: 23.219116
360 Cost: 22.973276
380 Cost: 22.73116
400 Cost: 22.492702
420 Cost: 22.25789
440 Cost: 22.026653
460 Cost: 21.798906
480 Cost: 21.57463
500 Cost: 21.353754
520 Cost: 21.136198
540 Cost: 20.921982
560 Cost: 20.710983
580 Cost: 20.503155
600 Cost: 20.298468
620 Cost: 20.096874
640 Cost: 19.898317
660 Cost: 19.70274
680 Cost: 19.510117
700 Cost: 19.3204
720 Cost: 19.133488
740 Cost: 18.949415
760 Cost: 18.768074
780 Cost: 18.58947
800 Cost: 18.413542
820 Cost: 18.240227
840 Cost: 18.069515
860 Cost: 17.901358
880 Cost: 17.735668
900 Cost: 17.572468
920 Cost: 17.411688
940 Cost: 17.253317
960 Cost: 17.097277
980 Cost: 16.943562
1000 Cost: 16.7921

In [8]:
Y

array([[152.],
       [185.],
       [180.],
       [196.],
       [142.],
       [101.],
       [149.],
       [115.],
       [175.],
       [164.],
       [141.],
       [141.],
       [184.],
       [152.],
       [148.],
       [192.],
       [147.],
       [183.],
       [177.],
       [159.],
       [177.],
       [175.],
       [175.],
       [149.],
       [192.]], dtype=float32)